/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
    	Car a = new Car("{engine}","{wheels}");
    	System.out.println(a.start());
    	
    	
        //System.out.println(new App().getGreeting());
    }
}
