/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
    	Car a = new Car("{engine}","{wheels}");
    	System.out.println(a.start());
    	
    	SportsCar b = new SportsCar ("{engine}","{wheels}","{lights}");
    	System.out.println(b.start());
    	System.out.println(b.speedOn());
    	
    	Truck c = new Truck ("{engine}","{wheels}","{payload}");
    	System.out.println(c.start());
    	System.out.println(c.load());
        //System.out.println(new App().getGreeting());
    }
}
